export const companyData = {
  fullName: "Общество с ограниченной ответственностью «Глобал Косметикс»",
  shortName: "ООО «Глобал Косметикс»",
  legalAddress: "199034, г. Санкт-Петербург, 1-я линия В.О., д. 12, литера А, помещ. 1-Н",
  postalAddress: "199034, г. Санкт-Петербург, 1-я линия В.О., д. 12, литера А, помещ. 1-Н",
  supportEmail: "hello@asaya.ru",
  supportEmailHref: "mailto:hello@asaya.ru",
  legalEmail: "asayacosmetics@yandex.ru",
  legalEmailHref: "mailto:asayacosmetics@yandex.ru",
  email: "asayacosmetics@yandex.ru",
  emailHref: "mailto:asayacosmetics@yandex.ru",
  inn: "7801715998",
  kpp: "780101001",
  ogrn: "1227800112825",
} as const;
