const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.PDP_TEST_URL||'http://127.0.0.1:3384',out='test-artifacts/rich-content-v2';fs.mkdirSync(out,{recursive:true});
const ts=require('typescript'),Module=require('node:module');
const mod=new Module(require('node:path').resolve('src/lib/store-data.ts'));
mod._compile(ts.transpileModule(fs.readFileSync('src/lib/store-data.ts','utf8').replace('import { assetPath } from "@/lib/asset-path";','const assetPath=(p:string)=>p;'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,require('node:path').resolve('src/lib/store-data.ts'));
const seeds=JSON.parse(fs.readFileSync('backend/data/pdp-rich-content-v2.json','utf8'));
const pdp=seeds.find(e=>e.sku==='1S-BA-02-02').pdp;
const slugs=['guava-shower-gel','coconut-body-cream','hair-balm','hair-shampoo','kiwi-shower-gel','strawberry-shower-gel'];
const skus=['1S-BA-02-02','1S-BA-03','1S-HK-03','1S-HK-01','1S-BA-02-04','1S-BA-02-01'];
const catalog=slugs.map((slug,i)=>{const p=mod.exports.defaultProducts.find(p=>p.id===slug);const {id,name,price,oldPrice,stock,active,rating,reviews,discount,...content}=p;return {sku:skus[i],slug,name,currency:'RUB',regularMinor:Math.max(price,oldPrice)*100,finalMinor:price*100,available:10,testMode:true,stockState:'known',content:{...content,safety:'',setKind:'none',...(i===0?{pdp}:{})}};});
const content=catalog[0].content,image=content.image,firstFaq=pdp.sections.find(s=>s.kind==='faq').items[0];
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){const c=await b.newContext({viewport:{width,height:960}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('asaya-cookie-choice-v1','essential'));
let revision=1,draft={sku:skus[0],slug:slugs[0],name:catalog[0].name,regularMinor:79900,finalMinor:79900,weightG:null,widthMm:null,heightMm:null,depthMm:null,content:{...content,pdp}},live=JSON.stringify(draft);
const id='10000000-0000-4000-8000-000000000001';
await p.route('**/*',async r=>{const u=new URL(r.request().url()),path=u.pathname,req=r.request();const json=(v,status=200)=>r.fulfill({status,contentType:'application/json',body:JSON.stringify(v)});if(u.origin!==base)return r.abort();
if(path==='/api/store/v1/products')return json({items:catalog});
if(path==='/api/admin/v1/auth/me')return json({user:{id,role:'admin',staffRole:'administrator'},csrfToken:'a'.repeat(64)});
if(path==='/api/admin/v1/products')return json({items:[{id,sku:skus[0],name:catalog[0].name,active:true,revision,category:'hair',image,lifecycle:'published'}],nextOffset:null});
if(path==='/api/admin/v1/products/'+id){if(req.method()==='PUT'){const body=req.postDataJSON();assert.equal(body.revision,revision);delete body.revision;draft=body;revision++;return json({id,revision});}return json({id,revision,active:true,hasDraft:true,everPublished:true,lifecycle:'published',publishedAt:'2026-09-22T00:00:00Z',draft,stocks:[]});}
if(path.startsWith('/api/'))return json({items:[],total:0,average:null},200);return r.continue();});
for(const slug of ['guava-shower-gel','coconut-body-cream']){await p.goto(base+'/product/'+slug+'/');await p.getByRole('heading',{level:1,name:catalog.find(p=>p.slug===slug).name}).waitFor();const info=p.getByRole('region',{name:'Информация о товаре'}),media=p.locator('[class*="galleryColumn"]').first();const before=await media.boundingBox();await info.locator('details').evaluateAll(ds=>ds.forEach(d=>d.open=true));const after=await media.boundingBox();assert.ok(Math.abs(before.height-after.height)<1);if(width===1440){const box=await info.boundingBox();assert.ok(Math.abs(box.height-after.height)<1);assert.equal(await info.evaluate(el=>getComputedStyle(el).overflowY),'auto');assert.ok(await info.evaluate(el=>el.scrollHeight>el.clientHeight));}else assert.equal(await info.evaluate(el=>getComputedStyle(el).overflowY),'visible');
assert.equal(await p.locator('[class*="recommendationGrid"] article').count(),4);if(width===1440)assert.ok(await p.locator('[class*="recommendationGrid"]').evaluate(e=>{const rail=e.getBoundingClientRect();return [...e.querySelectorAll('article')].every(a=>a.getBoundingClientRect().right<=rail.right+1)}),'All four recommendations must be visible');
if(slug==='guava-shower-gel'){const faq=p.locator('[data-rich-content] details').first();await faq.locator('summary').click();assert.equal(await faq.getAttribute('open'),'');await p.getByText(firstFaq.body,{exact:true}).waitFor();await faq.locator('summary').click();const rendered=await p.locator('[data-rich-content]').textContent();for(const s of pdp.sections)for(const text of [s.eyebrow,s.title,s.body,s.additionalBody,...s.items.flatMap(i=>[i.title,i.body])].filter(Boolean))assert.ok(rendered.includes(text),'Missing exact Figma copy: '+text);}else assert.equal(await p.locator('[data-rich-content]').count(),0);
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.locator('[data-rich-content] img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await p.waitForFunction(()=>[...document.querySelectorAll('[data-rich-content] img')].every(i=>i.complete&&i.naturalWidth>0));await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:out+'/'+slug+'-'+width+'.png',fullPage:true});}
await p.goto(base+'/admin/');await p.getByRole('button',{name:'Товары',exact:true}).click();await p.getByRole('button',{name:new RegExp('1S-BA-02-02')}).click();await p.getByRole('button',{name:'Rich Content',exact:true}).click();await p.locator('summary').filter({hasText:'Вопросы и ответы'}).click();await p.locator('summary').filter({hasText:'1. '+firstFaq.title}).click();await p.getByLabel(/^Ответ/).first().fill('Отредактированный ответ');await p.getByLabel('Включить Rich Content').uncheck();await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.getByText('Сохранено · Не опубликовано. Для изменения сайта нажмите «Опубликовать».',{exact:true}).waitFor();assert.equal(draft.content.pdp.enabled,false);assert.equal(draft.content.pdp.sections.find(s=>s.kind==='faq').items[0].body,'Отредактированный ответ');assert.equal(JSON.parse(live).content.pdp.enabled,true);await p.screenshot({path:out+'/admin-'+width+'.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PDP rich/legacy, geometry, FAQ, four recommendations, Admin draft save passed '+width);await c.close();}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
