const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.PDP_TEST_URL||'http://127.0.0.1:3382',out='test-artifacts/rich-content';fs.mkdirSync(out,{recursive:true});
const image='/images/figma/page2-packshots/hair-balm.webp';
const section=(kind,title,body,items=[],media=[])=>({kind,title,body,additionalBody:'',items,media});
const pdp={version:1,node:'418:2286',enabled:true,sections:[section('result','Результат из Admin','Описание результата',[{title:'Преимущество',body:'Данные товара'}],[{src:image}]),section('howTo','Применение из Admin','',[{title:'Шаг первый',body:'Текст шага',media:{src:image}},{title:'Шаг второй',body:'Другой текст',media:{src:image}}]),section('fragrance','Аромат из Admin','Текст аромата',[],[{src:image}]),section('ingredients','Компоненты из Admin','Описание компонентов',[],[{src:image}]),section('faq','Вопросы из Admin','',[{title:'Вопрос покупателя?',body:'Ответ из сохранённых данных.'}], [{src:image}])],recommendations:['SKU-2']};
const content={description:'Описание товара. '.repeat(20),volume:'300 мл',category:'hair',setKind:'none',usage:'Применение. '.repeat(30),ingredients:'Состав. '.repeat(50),aroma:'Аромат. '.repeat(20),image,gallery:[],badge:'',features:[],safety:'',instruction:{steps:[],amount:'',tip:''},recommendations:[],sensory:[]};
const catalog=['hair-balm','hair-shampoo','multi-hair-spray','coconut-body-cream','avocado-body-cream','hair-mask'].map((slug,i)=>({sku:'SKU-'+i,slug,name:'Товар '+i,currency:'RUB',regularMinor:79900,finalMinor:79900,available:10,testMode:true,stockState:'known',content:{...content,...(i===0?{pdp}:{})}}));
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){const c=await b.newContext({viewport:{width,height:960}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('asaya-cookie-choice-v1','essential'));
let revision=1,draft={sku:'SKU-0',slug:'hair-balm',name:'Товар 0',regularMinor:79900,finalMinor:79900,weightG:null,widthMm:null,heightMm:null,depthMm:null,content:{...content,pdp}},live=JSON.stringify(draft);
const id='10000000-0000-4000-8000-000000000001';
await p.route('**/*',async r=>{const u=new URL(r.request().url()),path=u.pathname,req=r.request();const json=(v,status=200)=>r.fulfill({status,contentType:'application/json',body:JSON.stringify(v)});if(u.origin!==base)return r.abort();
if(path==='/api/store/v1/products')return json({items:catalog});
if(path==='/api/admin/v1/auth/me')return json({user:{id,role:'admin',staffRole:'administrator'},csrfToken:'a'.repeat(64)});
if(path==='/api/admin/v1/products')return json({items:[{id,sku:'SKU-0',name:'Товар 0',active:true,revision,category:'hair',image,lifecycle:'published'}],nextOffset:null});
if(path==='/api/admin/v1/products/'+id){if(req.method()==='PUT'){const body=req.postDataJSON();assert.equal(body.revision,revision);delete body.revision;draft=body;revision++;return json({id,revision});}return json({id,revision,active:true,hasDraft:true,everPublished:true,lifecycle:'published',publishedAt:'2026-09-22T00:00:00Z',draft,stocks:[]});}
if(path.startsWith('/api/'))return json({items:[],total:0,average:null},200);return r.continue();});
for(const slug of ['hair-balm','hair-shampoo']){await p.goto(base+'/product/'+slug+'/');await p.getByRole('heading',{level:1,name:slug==='hair-balm'?'Товар 0':'Товар 1'}).waitFor();const info=p.getByRole('region',{name:'Информация о товаре'}),media=p.locator('[class*="galleryColumn"]').first();const before=await media.boundingBox();await info.locator('details').evaluateAll(ds=>ds.forEach(d=>d.open=true));const after=await media.boundingBox();assert.ok(Math.abs(before.height-after.height)<1);if(width===1440){const box=await info.boundingBox();assert.ok(Math.abs(box.height-after.height)<1);assert.equal(await info.evaluate(el=>getComputedStyle(el).overflowY),'auto');assert.ok(await info.evaluate(el=>el.scrollHeight>el.clientHeight));}else assert.equal(await info.evaluate(el=>getComputedStyle(el).overflowY),'visible');
assert.equal(await p.locator('[class*="recommendationGrid"] article').count(),4);
if(slug==='hair-balm'){const faq=p.locator('[data-rich-content] details');await faq.locator('summary').click();assert.equal(await faq.getAttribute('open'),'');await p.getByText('Ответ из сохранённых данных.',{exact:true}).waitFor();await faq.locator('summary').click();}else assert.equal(await p.locator('[data-rich-content]').count(),0);
assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:out+'/'+slug+'-'+width+'.png',fullPage:true});}
await p.goto(base+'/admin/');await p.getByRole('button',{name:'Товары',exact:true}).click();await p.getByRole('button',{name:/Товар 0.*SKU-0/}).click();await p.getByRole('button',{name:'Rich Content',exact:true}).click();await p.locator('summary').filter({hasText:'Вопросы и ответы'}).click();await p.locator('summary').filter({hasText:'1. Вопрос покупателя?'}).click();await p.getByLabel(/^Ответ/).fill('Отредактированный ответ');await p.getByLabel('Включить Rich Content').uncheck();await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.getByText('Сохранено · Не опубликовано. Для изменения сайта нажмите «Опубликовать».',{exact:true}).waitFor();assert.equal(draft.content.pdp.enabled,false);assert.equal(draft.content.pdp.sections.find(s=>s.kind==='faq').items[0].body,'Отредактированный ответ');assert.equal(JSON.parse(live).content.pdp.enabled,true);await p.screenshot({path:out+'/admin-'+width+'.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PDP rich/legacy, geometry, FAQ, four recommendations, Admin draft save passed '+width);await c.close();}}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});


