import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {testDatabase} from './postgres.js';
import {importWildberries} from '../src/review-import.js';
import {Engagement} from '../src/engagement.js';
let ctx:Awaited<ReturnType<typeof testDatabase>>;
before(async()=>{ctx=await testDatabase();});after(async()=>ctx?.stop());
test('WB preserves all matching reviews, star-only and duplicates in source; retry does not republish hidden reviews or reward imports',async()=>{
 const id=randomUUID(),actor=randomUUID();
 await ctx.db.pool.query("INSERT INTO products(id,sku,name,active) VALUES($1,'WB-SKU','Review product',true)",[id]);
 await ctx.db.pool.query("INSERT INTO users(id,role) VALUES($1,'admin')",[actor]);
 const row={sku:'wb-sku',rating:5,body:'',author:'Пользователь Wildberries',date:'2026-09-04T07:18:54+03:00'};
 const rows=[row,row,{...row,rating:1,body:'Сохранить опечаткку'}, {...row,sku:'missing'}, {...row,rating:9}];
 assert.deepEqual(await importWildberries(ctx.db,rows),{read:5,imported:3,missingSku:1,duplicateSkipped:0,invalid:1});
 const e=new Engagement(ctx.db),publicData=await e.publicReviews('WB-SKU');
 assert.equal(publicData.aggregate.count,3);assert.equal(publicData.aggregate.average,11/3);
 const review=publicData.items[0];assert.equal(review.author_display_name,row.author);
 await e.moderate(actor,review.id,{action:'hide'});
 assert.equal((await e.publicReviews('WB-SKU')).aggregate.count,2);
 assert.deepEqual(await importWildberries(ctx.db,rows),{read:5,imported:0,missingSku:1,duplicateSkipped:3,invalid:1});
 assert.equal((await e.publicReviews('WB-SKU')).aggregate.count,2);
 await e.moderate(actor,review.id,{action:'reply',reply:'Ответ ASAYA'});
 await e.moderate(actor,review.id,{action:'show'});
 const restored=(await e.publicReviews('WB-SKU')).items.find(r=>r.id===review.id);
 assert.equal(restored?.reply,'Ответ ASAYA');
 assert.equal((await ctx.db.pool.query('SELECT count(*)::int n FROM loyalty_ledger')).rows[0].n,0);
 assert.equal((await ctx.db.pool.query('SELECT count(*)::int n FROM customer_profiles')).rows[0].n,0);
 const meta=(await ctx.db.pool.query('SELECT replied_by,replied_at,moderated_at FROM product_reviews WHERE id=$1',[review.id])).rows[0];
 assert.equal(meta.replied_by,actor);assert.ok(meta.replied_at);assert.ok(meta.moderated_at);
});
