import {parseImageCrop} from './image-crop.ts';

export const pdpNodes=['440:2890','457:3502','457:4268','457:4920','457:5317','418:3505','418:3744','418:3983','418:4215','418:4470','418:4726','418:4981','418:2286','300:1010','315:1453','315:1859','315:2680','315:3149','334:1380','335:1878','315:1065','354:1485','360:1710','368:1627','383:2020'] as const;
export type PdpMedia={src:string;crop?:string;frame?:{x:number;y:number;width:number;height:number};layout?:{x:number;y:number;width:number;height:number;rotation:number;flipX:boolean;flipY:boolean}};
export type PdpSection={eyebrow?:string;visualAspectRatio?:number;kind:'result'|'feature'|'ingredients'|'howTo'|'lifehack'|'fragrance'|'faq';title:string;body:string;additionalBody:string;media:PdpMedia[];items:Array<{title:string;body:string;media?:PdpMedia}>};
export type PdpContent={enabled?:boolean;version:1;node:typeof pdpNodes[number];sections:PdpSection[];recommendations:string[]};
export function pdpMediaSources(p:PdpContent):string[]{return p.sections.flatMap(s=>[...s.media.map(m=>m.src),...s.items.flatMap(i=>i.media?[i.media.src]:[])]);}
const obj=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('INVALID_PDP');return v as Record<string,unknown>;};
const str=(v:unknown,max=10000)=>{if(typeof v!=='string'||v.length>max)throw new Error('INVALID_PDP');return v;};
const keys=(v:Record<string,unknown>,allowed:string[])=>{if(Object.keys(v).some(k=>!allowed.includes(k)))throw new Error('INVALID_PDP');};
export function parsePdpContent(raw:unknown):PdpContent{
 const p=obj(raw);keys(p,['enabled','version','node','sections','recommendations']);
 if(p.enabled!==undefined&&typeof p.enabled!=='boolean')throw new Error('INVALID_PDP');
 if(p.version!==1||!pdpNodes.includes(p.node as typeof pdpNodes[number])||!Array.isArray(p.sections)||p.sections.length>7||!Array.isArray(p.recommendations)||p.recommendations.length>20)throw new Error('INVALID_PDP');
 const media=(raw:unknown):PdpMedia=>{const m=obj(raw);keys(m,['src','crop','layout','frame']);const src=str(m.src,1000);let safe=/^\/images\/[A-Za-z0-9_./-]+$/.test(src)&&!src.includes('..')||/^\/api\/store\/v1\/media\/[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(src);try{const u=new URL(src);safe||=u.protocol==='https:'&&!u.username&&!u.password;}catch{}if(!safe)throw new Error('INVALID_PDP_MEDIA');if(m.crop!==undefined&&!parseImageCrop(str(m.crop,500)))throw new Error('INVALID_PDP_CROP');let layout:PdpMedia['layout'];if(m.layout!==undefined){const l=obj(m.layout);keys(l,['x','y','width','height','rotation','flipX','flipY']);if(!['x','y','width','height','rotation'].every(k=>typeof l[k]==='number'&&Number.isFinite(l[k])&&Math.abs(l[k] as number)<=1000)||Number(l.width)<=0||Number(l.height)<=0||typeof l.flipX!=='boolean'||typeof l.flipY!=='boolean')throw new Error('INVALID_PDP_LAYOUT');layout=l as PdpMedia['layout'];}let frame:PdpMedia['frame'];if(m.frame!==undefined){const f=obj(m.frame);keys(f,['x','y','width','height']);if(!['x','y','width','height'].every(k=>typeof f[k]==='number'&&Number.isFinite(f[k])&&Math.abs(f[k] as number)<=2000)||Number(f.width)<=0||Number(f.height)<=0)throw new Error('INVALID_PDP_FRAME');frame=f as PdpMedia['frame'];}return {src,...(frame?{frame}:{}),...(m.crop?{crop:m.crop as string}:{}),...(layout?{layout}:{})};};
 const seen=new Set<string>();const sections=p.sections.map(raw=>{const s=obj(raw);keys(s,['eyebrow','visualAspectRatio','kind','title','body','additionalBody','media','items']);const kind=str(s.kind);if(!['result','feature','ingredients','howTo','lifehack','fragrance','faq'].includes(kind)||seen.has(kind)||!Array.isArray(s.media)||s.media.length>4||!Array.isArray(s.items)||s.items.length>20)throw new Error('INVALID_PDP');seen.add(kind);if(s.visualAspectRatio!==undefined&&(typeof s.visualAspectRatio!=='number'||!Number.isFinite(s.visualAspectRatio)||s.visualAspectRatio<0.2||s.visualAspectRatio>5))throw new Error('INVALID_PDP');return {...(s.eyebrow!==undefined?{eyebrow:str(s.eyebrow,300)}:{}),...(s.visualAspectRatio!==undefined?{visualAspectRatio:s.visualAspectRatio as number}:{}),kind:kind as PdpSection['kind'],title:str(s.title,300),body:str(s.body),additionalBody:str(s.additionalBody),media:s.media.map(media),items:s.items.map(raw=>{const i=obj(raw);keys(i,['title','body','media']);return {title:str(i.title,1000),body:str(i.body),...(i.media?{media:media(i.media)}:{})};})};});
 return {...(p.enabled!==undefined?{enabled:p.enabled as boolean}:{}),version:1,node:p.node as PdpContent['node'],sections,recommendations:p.recommendations.map(v=>{const id=str(v,100);if(!/^[A-Za-z0-9][A-Za-z0-9_-]*$/.test(id))throw new Error('INVALID_PDP_RECOMMENDATION');return id;})};
}
