import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {Database,lock,type Tx} from './db.js';
import {DomainError} from './core.js';
const revision=z.number().int().nonnegative();
export const bannerSchema=z.object({enabled:z.boolean(),message:z.string().trim().max(2000),buttonText:z.string().trim().max(100),buttonUrl:z.string().trim().max(1000).refine(v=>!v||/^\/(?!\/)[^\s\\]*$/.test(v)||(()=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}})()),revision}).strict().refine(v=>!v.enabled||!!v.message);
export const testStockSchema=z.object({enabled:z.boolean(),quantity:z.number().int().min(0).max(1000000),revision}).strict();
async function admin(tx:Tx,actor:string){if(!(await tx.query("SELECT 1 FROM users WHERE id=$1 AND role='admin' AND NOT disabled FOR SHARE",[actor])).rowCount)throw new DomainError('FORBIDDEN',403);}
export class StorefrontControls{
 constructor(private db:Database,private production=true){}
 async banner(){const r=(await this.db.pool.query('SELECT * FROM storefront_banner WHERE singleton')).rows[0];return {enabled:r.enabled,message:r.message,buttonText:r.button_text,buttonUrl:r.button_url,revision:r.revision};}
 async saveBanner(actor:string,raw:unknown){const v=bannerSchema.parse(raw);return this.db.transaction(async tx=>{await admin(tx,actor);const result=await tx.query('UPDATE storefront_banner SET enabled=$1,message=$2,button_text=$3,button_url=$4,revision=revision+1 WHERE singleton AND revision=$5 RETURNING revision',[v.enabled,v.message,v.buttonText,v.buttonUrl,v.revision]);if(!result.rowCount)throw new DomainError('EDIT_CONFLICT');await tx.query("INSERT INTO audit_log(id,actor_id,action,entity_id,detail) VALUES($1,$2,'storefront.banner.saved','00000000-0000-4000-8000-000000000030',$3)",[randomUUID(),actor,JSON.stringify(v)]);return {revision:result.rows[0].revision};});}
 async stock(id:string){z.uuid().parse(id);const r=(await this.db.pool.query(`SELECT COALESCE(t.enabled,false) AS enabled,COALESCE(t.quantity,0) AS quantity,COALESCE(t.revision,0) AS revision,
 COALESCE((SELECT sum(GREATEST(0,LEAST(b.on_hand,asaya_stock_limit(p.id,w.id,$2))-b.reserved)) FROM inventory_balances b JOIN warehouses w ON w.id=b.warehouse_id WHERE b.product_id=p.id AND w.active),0)::integer AS real
 FROM products p LEFT JOIN product_test_stock t ON t.product_id=p.id WHERE p.id=$1`,[id,this.production])).rows[0];if(!r)throw new DomainError('PRODUCT_NOT_FOUND',404);return r as {enabled:boolean;quantity:number;revision:number;real:number};}
 async saveStock(actor:string,id:string,raw:unknown){z.uuid().parse(id);const v=testStockSchema.parse(raw);return this.db.transaction(async tx=>{await admin(tx,actor);await lock(tx,'test-stock:'+id);const p=(await tx.query('SELECT archived_at FROM products WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p)throw new DomainError('PRODUCT_NOT_FOUND',404);if(p.archived_at)throw new DomainError('PRODUCT_ARCHIVED');const prior=(await tx.query('SELECT revision FROM product_test_stock WHERE product_id=$1',[id])).rows[0];if((prior?.revision??0)!==v.revision)throw new DomainError('EDIT_CONFLICT');await tx.query('INSERT INTO product_test_stock(product_id,enabled,quantity,revision) VALUES($1,$2,$3,1) ON CONFLICT(product_id) DO UPDATE SET enabled=$2,quantity=$3,revision=product_test_stock.revision+1',[id,v.enabled,v.quantity]);await tx.query("INSERT INTO audit_log(id,actor_id,action,entity_id,detail) VALUES($1,$2,'product.test_stock.saved',$3,$4)",[randomUUID(),actor,id,JSON.stringify(v)]);return {revision:v.revision+1};});}
}
