'use client';
import {useEffect,useState} from 'react';
import {assetPath} from '@/lib/asset-path';
import {createStoreRequest,AuthClientError} from '@/lib/auth-client';
import {adminError,type StaffSession} from '@/lib/admin-client';
type Input={code:string;discount_percent:number;starts_at:string|null;ends_at:string|null;is_active:boolean;allow_repeat_use:boolean;max_total_uses:number|null;max_uses_per_customer:number|null;label:string};
type Row=Input&{id:string;used:number;discount_total_minor:string};
type Preview={row:number;data:Input|null;error:string|null};
const blank=():Input=>({code:'',discount_percent:10,starts_at:null,ends_at:null,is_active:true,allow_repeat_use:false,max_total_uses:null,max_uses_per_customer:1,label:''});
const request=createStoreRequest(assetPath('/api/admin/v1'),fetch);
const errors:Record<string,string>={PROMO_DUPLICATE:'Такой промокод уже существует.',PROMO_EXPIRED:'Укажите будущую дату окончания перед включением.',PROMO_IMPORT_CHANGED:'Данные изменились. Повторите проверку файла.',PROMO_CSV_INVALID:'Проверьте формат CSV и заголовки по шаблону.',PROMO_CSV_TOO_LARGE:'Максимум 500 строк и 500 КБ.',PROMO_CODE_IMMUTABLE:'Код существующего промокода менять нельзя.'};
export function AdminPromos({session,onExpired}:{session:StaffSession;onExpired:()=>void}){
 const [view,setView]=useState('active'),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState<Row[]>([]),[total,setTotal]=useState(0),[next,setNext]=useState<number|null>(null),[selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<Input|null>(null),[id,setId]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0),[csv,setCsv]=useState(''),[preview,setPreview]=useState<Preview[]>([]),[confirm,setConfirm]=useState<'disable'|'archive'|'import'|null>(null);
 function fail(e:unknown){if(e instanceof AuthClientError&&e.code==='UNAUTHENTICATED')onExpired();setNotice(e instanceof AuthClientError?(errors[e.code]??adminError(e)):e instanceof Error?e.message:'Не удалось выполнить действие.');}
 useEffect(()=>{let live=true;setRows([]);setSelected([]);void request('promos?'+new URLSearchParams({view,search,offset:String(offset)}),'GET').then(v=>{if(live){const r=v as {items:Row[];total:number;nextOffset:number|null};setRows(r.items);setTotal(r.total);setNext(r.nextOffset);}}).catch(e=>{if(live)fail(e);});return()=>{live=false;};},[view,search,offset,refresh]);
 async function action(work:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await work();}catch(e){fail(e);}finally{setBusy(false);}}
 function open(row?:Row){setId(row?.id??null);setEdit(row?Object.fromEntries(Object.keys(blank()).map(k=>[k,row[k as keyof Input]])) as Input:blank());}
 const valid=preview.filter(r=>r.data);
 return <section aria-label="Промокоды"><h2>Промокоды</h2><p>Настройки и предварительный расчёт готовы. Использование промокода при оплате ещё не включено.</p>{notice&&<p role="status">{notice}</p>}
 <fieldset disabled={busy}><div><button type="button" aria-pressed={view==='active'} onClick={()=>{setView('active');setOffset(0);}}>Активные</button><button type="button" aria-pressed={view==='archive'} onClick={()=>{setView('archive');setOffset(0);}}>Архив</button><button type="button" onClick={()=>open()}>Создать промокод</button></div>
 <label>Поиск по коду или комментарию<input value={search} maxLength={100} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></label><p>Всего: {total}. Выбрано: {selected.length}</p>
 <label><input type="checkbox" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.id):[])}/>Выбрать страницу</label>
 <button type="button" disabled={!selected.length} onClick={()=>setConfirm('disable')}>Отключить выбранные</button><button type="button" disabled={!selected.length} onClick={()=>setConfirm('archive')}>В архив</button>
 <div style={{overflowX:'auto'}}><table><thead><tr><th>Выбор</th><th>Код</th><th>Скидка</th><th>Срок</th><th>Оплаченных использований</th><th>Сумма скидок</th><th>Действия</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><input aria-label={'Выбрать '+r.code} type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(i=>i!==r.id))}/></td><td>{r.code}<small>{r.label}</small></td><td>{r.discount_percent}%</td><td>{r.ends_at?new Date(r.ends_at).toLocaleString('ru-RU'):'Без окончания'}</td><td>{r.used}</td><td>{Number(r.discount_total_minor)/100} ₽</td><td><button type="button" onClick={()=>open(r)}>Параметры / восстановить</button></td></tr>)}</tbody></table></div>
 <button type="button" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Назад</button><button type="button" disabled={next===null} onClick={()=>setOffset(next!)}>Далее</button>
 {edit&&<form onSubmit={e=>{e.preventDefault();void action(async()=>{await request(id?'promos/'+id:'promos',id?'PUT':'POST',edit,session.csrfToken);setEdit(null);setRefresh(v=>v+1);setNotice('Промокод сохранён.');});}}><h3>{id?'Параметры промокода':'Новый промокод'}</h3>
 <label>Код<input required maxLength={40} disabled={!!id} value={edit.code} onChange={e=>setEdit({...edit,code:e.target.value})}/></label>{!id&&<button type="button" onClick={()=>void action(async()=>{const r=await request('promos/generate','POST',{},session.csrfToken) as {code:string};setEdit({...edit,code:r.code});})}>Сгенерировать код</button>}
 <label>Скидка, %<input type="number" required min={1} max={100} step={1} value={edit.discount_percent} onChange={e=>setEdit({...edit,discount_percent:Number(e.target.value)})}/></label>
 {(['starts_at','ends_at'] as const).map(k=><label key={k}>{k==='starts_at'?'Начало':'Окончание'} (местное время)<input type="datetime-local" value={edit[k]?new Date(new Date(edit[k]!).getTime()-new Date(edit[k]!).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>setEdit({...edit,[k]:e.target.value?new Date(e.target.value).toISOString():null})}/></label>)}
 <label><input type="checkbox" checked={edit.is_active} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/>Включён (также восстанавливает из архива)</label>
 <label><input type="checkbox" checked={edit.allow_repeat_use} onChange={e=>setEdit({...edit,allow_repeat_use:e.target.checked,max_uses_per_customer:e.target.checked?null:1})}/>Разрешить повторное использование</label>
 {(['max_total_uses','max_uses_per_customer'] as const).map(k=><label key={k}>{k==='max_total_uses'?'Общий лимит':'Лимит на покупателя'} (пусто — без лимита)<input type="number" min={1} max={100000000} step={1} disabled={k==='max_uses_per_customer'&&!edit.allow_repeat_use} value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value?Number(e.target.value):null})}/></label>)}
 <p>Лимит на покупателя требует входа в аккаунт. Без него промокод доступен гостям.</p><label>Комментарий<input maxLength={300} value={edit.label} onChange={e=>setEdit({...edit,label:e.target.value})}/></label><button type="submit">Сохранить промокод</button><button type="button" onClick={()=>setEdit(null)}>Закрыть</button></form>}
 <h3>Импорт CSV</h3><a href={assetPath('/api/admin/v1/promos/template')}>Скачать шаблон CSV</a><p>UTF-8, разделитель запятая; даты ISO 8601 с часовым поясом. До 500 строк / 500 КБ. Сначала проверка, затем подтверждение.</p><label>Файл CSV<input type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];setCsv('');setPreview([]);if(f)void action(async()=>{if(f.size>500000)throw Error('Максимальный размер — 500 КБ.');const text=await f.text();const p=await request('promos/import-preview','POST',{csv:text},session.csrfToken) as Preview[];setCsv(text);setPreview(p);});}}/></label>
 {preview.length>0&&<><p>Корректных строк: {valid.length} из {preview.length}</p><ul>{preview.map(r=><li key={r.row}>Строка {r.row}: {r.error??r.data?.code+' — готово'}</li>)}</ul><button type="button" disabled={!valid.length} onClick={()=>setConfirm('import')}>Импортировать корректные строки</button></>}
 {confirm&&<div role="alert"><p>Подтвердите {confirm==='import'?'импорт '+valid.length+' строк':(confirm==='archive'?'архивацию':'отключение')+' '+selected.length+' промокодов'}.</p><button type="button" onClick={()=>void action(async()=>{const r=await request(confirm==='import'?'promos/import':'promos/bulk','POST',confirm==='import'?{csv,rows:valid.map(r=>r.row),confirmed:true}:{ids:selected,action:confirm,confirmed:true},session.csrfToken) as {count:number};setNotice('Обработано: '+r.count);setConfirm(null);setSelected([]);setPreview([]);setRefresh(v=>v+1);})}>Подтвердить</button><button type="button" onClick={()=>setConfirm(null)}>Отмена</button></div>}
 </fieldset></section>;
}
