'use client';
import {useEffect,useState} from 'react';
import {assetPath} from '@/lib/asset-path';
import {createStoreRequest} from '@/lib/auth-client';
import {adminError,type StaffSession} from '@/lib/admin-client';
import {badgeOptions,categoryLabels} from '@/lib/store-data';
import {useShop} from './shop-provider';
import styles from './admin-operations.module.css';
export type PriceRow={id:string;sku:string;name:string;category:string;image:string;badge:string;lifecycle:string;revision:number;regularMinor:number|null;finalMinor:number|null};
export const operations=createStoreRequest(assetPath('/api/admin/v1'),fetch);
export function useDirtyWarning(dirty:boolean){useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);}
const status:Record<string,string>={published:'Опубликован',unpublished:'Скрыт',draft:'Черновик'};
export function AdminPrices({session,onDirty}:{session:StaffSession;onDirty:(v:boolean)=>void}){
 const {reloadCatalog}=useShop();const [rows,setRows]=useState<PriceRow[]>([]),[edits,setEdits]=useState<Record<string,PriceRow>>({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[state,setState]=useState(''),[badge,setBadge]=useState(''),[sort,setSort]=useState('name');const dirty=Object.keys(edits).length>0;useDirtyWarning(dirty);useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 useEffect(()=>{operations('prices','GET').then(r=>setRows((r as {items:PriceRow[]}).items)).catch(e=>setNotice(adminError(e)));},[]);
 const update=(r:PriceRow,p:Partial<PriceRow>)=>setEdits(v=>({...v,[r.id]:{...r,...p}}));
 async function save(r:PriceRow){setBusy(true);setNotice('');try{await operations('prices/'+r.id,'PUT',{revision:r.revision,regularMinor:r.regularMinor,finalMinor:r.finalMinor,badge:r.badge},session.csrfToken);setRows(v=>v.map(p=>p.id===r.id?{...r,revision:r.revision+1}:p));setEdits(v=>{const n={...v};delete n[r.id];return n;});reloadCatalog();setNotice('Цена и метка сохранены. Видимость товара не изменена.');}catch(e){setNotice(adminError(e));}finally{setBusy(false);}}
 const visible=rows.filter(r=>(r.name+' '+r.sku).toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))&&(!category||r.category===category)&&(!state||r.lifecycle===state)&&(!badge||r.badge===badge)).sort((a,b)=>sort==='price'?(a.finalMinor??0)-(b.finalMinor??0):sort==='price-desc'?(b.finalMinor??0)-(a.finalMinor??0):sort==='category'?a.category.localeCompare(b.category):a.name.localeCompare(b.name,'ru'));
 const price=(r:PriceRow,k:'regularMinor'|'finalMinor',label:string)=><input aria-label={label+' '+r.sku} inputMode="decimal" type="number" min="0" max="10000000000" step="0.01" value={r[k]===null?'':r[k]!/100} onChange={e=>update(r,{[k]:e.target.value===''?null:Math.round(Number(e.target.value)*100)})}/>;
 return <section><h1>Цены</h1><p>Цены в рублях. Явное сохранение применяет только цену и метку, не затрагивая другие поля карточки.</p>{notice&&<p role="status">{notice}</p>}<div className={styles.filters}><label>Название или SKU<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Категория<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Все</option>{Object.entries(categoryLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Видимость<select value={state} onChange={e=>setState(e.target.value)}><option value="">Все</option>{Object.entries(status).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Метка<select value={badge} onChange={e=>setBadge(e.target.value)}><option value="">Все</option>{badgeOptions.filter(Boolean).map(v=><option key={v}>{v}</option>)}</select></label><label>Сортировка<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Название</option><option value="price">Цена ↑</option><option value="price-desc">Цена ↓</option><option value="category">Категория</option></select></label></div><div className={styles.table}><table><thead><tr><th>Товар</th><th>Обычная цена, ₽</th><th>Цена продажи, ₽</th><th>Скидка</th><th>Метка</th><th>Сохранение</th></tr></thead><tbody>{visible.map(original=>{const r=edits[original.id]??original;return <tr key={r.id}><td><div className={styles.product}>{r.image&&<img src={r.image.startsWith('/')?assetPath(r.image):r.image} alt=""/>}<div><strong>{r.name}</strong><small>{r.sku} · {categoryLabels[r.category as keyof typeof categoryLabels]} · {status[r.lifecycle]}</small></div></div></td><td>{price(r,'regularMinor','Обычная цена')}</td><td>{price(r,'finalMinor','Цена продажи')}</td><td>{r.regularMinor&&r.finalMinor!==null?Math.round((r.regularMinor-r.finalMinor)/r.regularMinor*100)+'%':'—'}</td><td><select aria-label={'Метка '+r.sku} value={r.badge} onChange={e=>update(r,{badge:e.target.value})}>{badgeOptions.map(v=><option key={v} value={v}>{v||'Без метки'}</option>)}</select></td><td>{edits[r.id]&&<small>Не сохранено</small>}<button disabled={busy||!edits[r.id]||r.regularMinor===null||r.finalMinor===null||r.finalMinor>r.regularMinor} onClick={()=>void save(r)}>Сохранить</button></td></tr>;})}</tbody></table></div></section>;
}
