'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {assetPath} from '@/lib/asset-path';
import {AuthClientError} from '@/lib/auth-client';
import {adminError,type StaffSession} from '@/lib/admin-client';
import {createStaffAccessClient,accessTxt,type Employee,type Invite} from '@/lib/staff-access-client';
import styles from './server-admin.module.css';
const api=createStaffAccessClient(assetPath('/api/admin/v1'));
const roles={owner:'Владелец',administrator:'Администратор',manager:'Менеджер'},statuses={pending:'Ожидает активации',active:'Активен',disabled:'Отключён'};
function download(text:string,name:string){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function AdminEmployees({session,onExpired}:{session:StaffSession;onExpired:()=>void}){
 const [items,setItems]=useState<Employee[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('manager'),[invite,setInvite]=useState<Invite|null>(null);
 const [confirm,setConfirm]=useState<{employee:Employee;action:string;role?:string}|null>(null);
 async function refresh(){setItems(await api.list());}
 function fail(e:unknown){setNotice(adminError(e));if(e instanceof AuthClientError&&e.code==='UNAUTHENTICATED')onExpired();}
 useEffect(()=>{void refresh().catch(fail);},[]);
 function offerFile(v:Invite){setInvite(v);download(accessTxt(v,window.location.href),'ASAYA-access.txt');}
 async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{offerFile(await api.create({name,email:email.trim().toLowerCase(),role},session.csrfToken));setName('');setEmail('');await refresh();}catch(e){fail(e);}finally{setBusy(false);}}
 async function change(){if(!confirm||busy)return;setBusy(true);setNotice('');try{const v=await api.change(confirm.employee.id,confirm.action,session.csrfToken,confirm.role);if(v)offerFile(v);setConfirm(null);await refresh();}catch(e){fail(e);}finally{setBusy(false);}}
 const actionLabels:Record<string,string>={delete:'Удалить сотрудника',disable:'Отключить доступ',enable:'Включить доступ',reset:'Сбросить пароль и 2FA',role:'Изменить роль'};
 return <section><h1>Сотрудники</h1><p>Права и доступ меняются сразу. Временный пароль действует 7 дней, сотрудник сам подключает 2FA.</p>{notice&&<p role="alert">{notice}</p>}
 <form onSubmit={create}><fieldset disabled={busy}><legend>Добавить сотрудника</legend><label>Имя<input required maxLength={150} value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Роль<select value={role} onChange={e=>setRole(e.target.value)}><option value="manager">Менеджер</option><option value="administrator">Администратор</option></select></label><button className={styles.primary}>Создать и скачать TXT</button></fieldset></form>
 {invite&&<aside role="status"><p>Файл доступа подготовлен. Передайте его сотруднику лично. Если загрузка не началась, скачайте файл кнопкой ниже.</p><button onClick={()=>download(accessTxt(invite,window.location.href),'ASAYA-access.txt')}>Скачать TXT повторно</button><button onClick={()=>setInvite(null)}>Закрыть</button></aside>}
 <div style={{overflowX:'auto'}}><table><thead><tr>{['Имя','Email','Роль','Статус','2FA','Последний вход','Действия'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{items.map(e=><tr key={e.id}><td>{e.name||'—'}</td><td>{e.email}</td><td>{roles[e.role]}</td><td>{statuses[e.status]}</td><td>{e.twoFactor?'Активна':'Не настроена'}</td><td>{e.lastLogin?new Date(e.lastLogin).toLocaleString('ru-RU'):'—'}</td><td>{e.role==='owner'?<span>Владелец защищён</span>:<><select aria-label={'Роль '+e.email} disabled={busy} value={e.role} onChange={event=>setConfirm({employee:e,action:'role',role:event.target.value})}><option value="manager">Менеджер</option><option value="administrator">Администратор</option></select>{[e.status==='disabled'?'enable':'disable','reset','delete'].map(action=><button key={action} disabled={busy} onClick={()=>setConfirm({employee:e,action})}>{actionLabels[action]}</button>)}</>}</td></tr>)}</tbody></table></div>
 {confirm&&<div role="dialog" aria-modal="true" aria-label="Подтверждение изменения доступа" className={styles.confirm}><p>{actionLabels[confirm.action]}: {confirm.employee.email}{confirm.role?' → '+roles[confirm.role as keyof typeof roles]:''}?</p>{['delete','disable','reset'].includes(confirm.action)&&<p>Действующие сессии будут отозваны. История действий сохранится.</p>}<button disabled={busy} onClick={()=>void change()}>Подтвердить</button><button disabled={busy} onClick={()=>setConfirm(null)}>Отмена</button></div>}
 </section>;
}
export function StaffActivation({onDone,onBack}:{onDone:(s:StaffSession)=>void;onBack:()=>void}){
 const [state,setState]=useState<{stage:'password'|'totp';csrfToken:string}|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[code,setCode]=useState(''),[setup,setSetup]=useState<{secret:string;qrSvg:string}|null>(null),[result,setResult]=useState<{session:StaffSession;recoveryCodes:string[]}|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{api.me().then(setState).catch(e=>setNotice(adminError(e)));},[]);
 useEffect(()=>{if(state?.stage==='totp')api.setup().then(setSetup).catch(e=>setNotice(adminError(e)));},[state?.stage]);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{if(!state){setState(await api.start(email,password));setPassword('');}else if(state.stage==='password'){if(password!==repeat){setNotice('Пароли не совпадают.');return;}await api.password(password,state.csrfToken);setPassword('');setRepeat('');setState({...state,stage:'totp'});}else{setResult(await api.confirm(code,state.csrfToken));setSetup(null);setCode('');}}catch(e){setNotice(adminError(e));}finally{setBusy(false);}}
 if(result)return <section className={styles.login}><h1>Доступ настроен</h1><p>Сохраните резервные коды. Они показаны только сейчас; каждый можно использовать один раз вместо кода приложения.</p><pre>{result.recoveryCodes.join('\n')}</pre><button onClick={()=>download('ASAYA — резервные коды\n'+result.recoveryCodes.join('\n'),'ASAYA-recovery-codes.txt')}>Скачать резервные коды</button><button onClick={()=>onDone(result.session)}>Коды сохранены — открыть Admin</button></section>;
 return <form className={styles.login} onSubmit={submit}><h1>{!state?'Первый вход / восстановление доступа':state.stage==='password'?'Установите личный пароль':'Подключите своё приложение-аутентификатор'}</h1>{notice&&<p role="alert">{notice}</p>}<fieldset disabled={busy}>
 {!state?<><label>Email<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Одноразовый временный пароль<input type="password" autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label></>:state.stage==='password'?<><label>Новый пароль — минимум 14 символов<input type="password" autoComplete="new-password" required minLength={14} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Повторите новый пароль<input type="password" autoComplete="new-password" required value={repeat} onChange={e=>setRepeat(e.target.value)}/></label></>:<>{setup?<><img alt="QR для подключения личного TOTP" width={240} height={240} src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(setup.qrSvg)}/><p>Или введите ключ вручную:</p><code style={{overflowWrap:'anywhere'}}>{setup.secret}</code></>:<p>Подготавливаем QR…</p>}<label>Код из приложения<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label></>}
 <button className={styles.primary} disabled={state?.stage==='totp'&&!setup}>{state?.stage==='totp'?'Подтвердить 2FA':'Продолжить'}</button><button type="button" onClick={onBack}>Вернуться ко входу</button></fieldset></form>;
}
